### PR TITLE
Matcher stuff

### PR DESCRIPTION
**Pull request by ajratner**
Refactors the basic candidate extractor object (now called `CandidateExtractor` for clarity) to be _compositional_.

In part this was because of requests for intersection operations, and the semantics of what an `Intersection` operator should be were slightly unclear/ambiguous, whereas compositional operators seemed better.

For example, suppose we want all phrases which (a) match a dictionary `d` and (b) contain the sub-phrase `gener` (ex from #112); now we can write:
```python
RegexFilterConcat(DictionaryMatch(label='D', dictionary=d), regex_pattern=r'.*gener')
```

Or, another request from the hackathon, all noun phrases matching a dictionary:
```python
RegexFilterAll(DictionaryMatch(label='D', dictionary=d), regex_pattern=r'NN.*')
```

@henryre when you get a chance this week could you take a look at this and see if it makes sense?  This adds a bit of complexity for the ddlite-developer but ultimately I hope it makes the ddlite-user's experience cleaner... but let's discuss

If we can agree on something here, then you can add in to the demo examples, and then we can add in the fuzzy phrase matching in this new format

### CODE REVIEW

**Comment by ajratner** [comment]
Fixes #112.  Fixes #121.

**Comment by ajratner** [comment]
@henryre note also that we have to tweak your original regex ngram matcher (which I renamed `RegexNgramMatcher` for clarity), got lazy here...

**Comment by henryre** [comment]
Sounds good. Will check it out and make the demos/Travis run

**Comment by henryre** [comment]
@ajratner LOVE the use of `re.compile()`

**Comment by henryre** [comment]
Need to update documentation on using matchers, but the examples have some now. Compositional instead of intersection is the right design choice here. Thus, LGTM!

**Pull request merged**
