### PR TITLE
Speed up learning with sparse operations and friends

### LINKED ISSUE #13: Extend logistic regression functions to handle scipy.csr_matrix
Support sparse matrices as optional input

### PR DESCRIPTION
**Pull request by henryre**
Vectorization and a few other tweaks give a 2000x speed up on a 100 observation, 4K feature problem (full gene example couldn't be run with the old methods)
Using the sparse methods gives an *additional* 50x speed up on the full gene example notebook
Sampling methods for SGD sped up similarly

Fixes #13

### CODE REVIEW

**Comment by chrismre** [comment]
WOW!

**Comment by ajratner** [comment]
Awesome!

Quick comments:

- Do we need a way to insert a rule set which replaces the existing rule set, rather than extends it?
- Aside from this, if it's running feel free to merge- I'll do a more careful review of the log reg code & compare with the latest version I have in Julia later (perhaps when we add L1), but looks good for now!

**Comment by ajratner** [comment]
@henryre I'd say once you've considered the minor thing I noted above, go ahead and merge!  And we can do another run over all the learning & inference code together this coming week too

**Comment by henryre** [comment]
Good point. I'll make the fix and merge in the AM

**Comment by ajratner** [comment]
Sounds great!

**Pull request merged**
